### ISSUE TITLE
logo design

### ISSUE THREAD

**Issue by Batarian711** [infominer33/web-work#1]
Hi. I am a graphic designer. I volunteer to design a logo for open source projects. I can design it for you to use it in the readme file. What dou you say?

**Comment by infominer33** [comment]
oh hi! sure! sounds great!

I looked to see if you used the same name anywhere else and checked out your [steemit blog](https://steemit.com/@batarian71). 
Impressive portfolio!

if you use any text `Webwork.tools` is the name of the website https://infominer.id/web-work .. 
I have the domain already, but I haven't messed with that part of it yet.
