### ISSUE TITLE
Fix punctuation 

### ISSUE THREAD

**Issue by MichaelCurrin** [infominer33/web-work#5]
On the github starter pack site you have this

¡!Create an index.md page¡!

It looks out of place and has no markdown benefit so maybe just remove the punctuation.

**Comment by infominer33** [comment]
Thanks for the suggestion! I was just using that to draw attention to an important point... but maybe just a little too wild and crazy :)

**Comment by MichaelCurrin** [comment]
Try using **bold**. Or have note at the top of the page in a different color that points to it.

**Comment by infominer33** [comment]
done and done
