### ISSUE TITLE
Downgrade to jekyll 3.9

### ISSUE THREAD

**Issue by MichaelCurrin** [infominer33/web-work#6]
Your Gemfile doesn't lock Jekyll and your lock file says 4.1.1

Unfortunately, GitHub Pages only support Jekyll 3.9 and there are plans to get this to 4 soon.

For local building it would help to match what GitHub Pages uses. For example the `link` jekyll tag works differently.

You'd have to lock all the gems to what is used on GitHub Pages.

I have a Gemfile where I do this.

https://github.com/MichaelCurrin/jekyll-blog-demo/blob/master/Gemfile

I am happy to help with a PR to update Gemfile and lock file if you need

**Comment by infominer33** [comment]
Heyyy! another great suggestion!!! much appreciated!
