### ISSUE TITLE
Remove cache files

### ISSUE THREAD

**Issue by MichaelCurrin** [infominer33/web-work#7]
Delete the two cache directories and add them to .gitignore

```
.jekyll-cache/
.sass-cache/
```

Here is my template file

https://github.com/MichaelCurrin/jekyll-blog-demo/blob/master/.gitignore

It includes ignoring the vendor and bundler directories relating to installing gems with bundler.

**Comment by infominer33** [comment]
I was thinking I could drop those! thanks for the confirmation!

**Comment by MichaelCurrin** [comment]
The update looks good.
